import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Slider from "@/components/Homepage/Slider";
import { Container } from "@/styles/Global";
import PopularCategory from "@/components/Homepage/PopularCategory";
import Banner from "@/components/Homepage/Banner";
import BestOffer from "@/components/Homepage/BestOffer";
import Campaigns from "@/components/Homepage/Campaigns";
import BestSellers from "@/components/Homepage/BestSellers";
import Opportunities from "@/components/Homepage/Opportunities";
import PasajNews from "@/components/Homepage/PasajNews";
import LastViews from "@/components/Homepage/LastViews";
import WhyPasaj from "@/components/Homepage/WhyPasaj";
import localFont from 'next/font/local'
import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query";
import { fetchAllProducts } from "@/lib/server";

const Greycliff = localFont({ src: './GreycliffCF-Medium.woff2' })


export const getStaticProps = async () => {
  const queryclient = new QueryClient();
  await queryclient.prefetchQuery(
  { queryKey: ['products'],
    queryFn: fetchAllProducts,}
  );

  return {
    props: {
      dehydratedState: dehydrate(queryclient),
    }
  }
}

export default function Home() {

  const { data } = useQuery({
    queryKey: ["products"],
    queryFn: fetchAllProducts,
  });
  console.log(data)

  return (
    <>
      <Head>
        <title>Turkcell Pasaj</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Greycliff.className}>
        <Slider />
        <Container>
          <PopularCategory />
          <Banner />
          <BestOffer data={data} />
          <Campaigns />
          <BestSellers data={data}/>
          <Opportunities />
          <PasajNews data={data}/>
          <LastViews data={data}/>
        </Container>
          <WhyPasaj />
      </main>
    </>
  );
}
